apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-prod
  template:
    metadata:
      labels:
        app: backend-prod
    spec:
      containers:
        - name: backend-prod
          image: <image-name>
          volumeMounts:
            - name: static-volume-prod
              mountPath: /home/appuser/app/staticfiles
          env:
            - name: POSTGRES_DB
              value: <postgres-db>
            - name: POSTGRES_USER
              value: <postgres-user>
            - name: POSTGRES_PASSWORD
              value: <postgres-password>
            - name: DJANGO_ENV
              value: <django-env>
      volumes:
        - name: static-volume-prod
          emptyDir: {}
      imagePullSecrets:
        - name: <image-pull-secret>
      initContainers:
        - name: migrate
          image: <migrate-image>
          command: ["python", "manage.py", "migrate"]
          env:
            - name: POSTGRES_DB
              value: <postgres-db>
            - name: POSTGRES_USER
              value: <postgres-user>
            - name: POSTGRES_PASSWORD
              value: <postgres-password>
          volumeMounts:
            - name: static-volume-prod
              mountPath: /home/appuser/app/staticfiles
      restartPolicy: Always