apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-prod-ingress
  labels:
    app: backend-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
spec:
  rules:
    - host: sis.vmt.gov.py
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: backend-prod-service
                port:
                  number: 8000
  tls:
    - hosts:
        - sis.vmt.gov.py
      secretName: backend-prod-tls