apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: pyaha-backend
type: Opaque
data:
  DJANGO_SECRET_KEY: [django-secret-key-codificado-en-base64]
---
apiVersion: v1
kind: Secret
metadata:
  name: email-config
  namespace: pyaha-backend
type: Opaque
data:
  EMAIL_USER: [email-user-codificado-en-base64]
  EMAIL_PASSWORD: [email-password-codificado-en-base64]
