apiVersion: v1
kind: Service
metadata:
  name: backend-prod-service  # Modificado para coincidir con la configuración del Ingress
  namespace: pyaha-backend
spec:
  selector:
    app: backend-prod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP