apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-prod
  template:
    metadata:
      labels:
        app: traefik-prod
    spec:
      containers:
        - name: traefik-prod
          image: traefik:latest
          command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.myresolver.acme.email=tuemail@ejemplo.com"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: letsencrypt
              mountPath: /letsencrypt
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: letsencrypt
          hostPath:
            path: /path/to/letsencrypt