apiVersion: v1
kind: Service
metadata:
  name: traefik-prod
spec:
  selector:
    app: traefik-prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443