apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
        - name: nginx-prod
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: static-volume-prod
              mountPath: /usr/share/nginx/html/static
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: static-volume-prod
          persistentVolumeClaim:
            claimName: static-volume-prod