apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-prod
  template:
    metadata:
      labels:
        app: db-prod
    spec:
      containers:
        - name: db-prod
          image: postgis/postgis:16-3.4-alpine
          volumeMounts:
            - name: postgres-data-prod
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: ${POSTGRES_DB}
            - name: POSTGRES_USER
              value: ${POSTGRES_USER}
            - name: POSTGRES_PASSWORD
              value: ${POSTGRES_PASSWORD}
      volumes:
        - name: postgres-data-prod
          persistentVolumeClaim:
            claimName: postgres-data-prod